server:
  port: 5056
spring:
  application:
    name: cg_demo


  #datasource:
    #url: jdbc:mysql://localhost:3306/count?characterEncoding=utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/count?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    driverClassName:



